# wallust.toml needs to include this
# alacritty = { template = 'alacritty.toml', target = '~/.config/alacritty/colors.toml' }
# and alacritty.toml should import that file under [general]
[colors.primary]
background = "#0E0F13"
foreground = "#B6B8BC"

[colors.normal]
black   = "#323336"
red     = "#5D626B"
green   = "#758092"
yellow  = "#738393"
blue    = "#8F9DB0"
magenta = "#94C3D3"
cyan    = "#C1CBD9"
white   = "#8E9197"

[colors.bright]
black   = "#63666A"
red     = "#5D626B"
green   = "#758092"
yellow  = "#738393"
blue    = "#8F9DB0"
magenta = "#94C3D3"
cyan    = "#C1CBD9"
white   = "#8E9197"
